server:
  port: 9003
spring:
  datasource:
#    driver-class-name: org.h2.Driver
#    initialize: false
#    name: foodboxdb
#    password: password
#    url: jdbc:h2:file:./foodboxdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
#    username: admin
     driver-class-name: com.mysql.cj.jdbc.Driver
     initialize: false
     name: capstone
     password: password123
     url: jdbc:mysql://localhost:3306/capstone
     username: root
     dialect: org.hibernate.dialect.MySQLDialect
#  h2:
#    console:
#      enabled: true
#      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    
# ...  
